arb-dir: lib/l10n
template-arb-file: app_pl.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
preferred-supported-locales:
  - pl
nullable-getter: false
format: true
